Repository eslint/code-explorer, pull requests merged in 2024-10, with the labels that each got.

#58 fix: minor glitches in the right pane
  src/lib/render-value.ts
Labels: bug

#63 feat: use playground themes
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/codemirror-themes.css
  src/components/ast/javascript-ast-tree-item.tsx
  src/components/ast/json-ast-tree-item.tsx
  src/components/ast/markdown-ast-tree-item.tsx
  src/components/cta.tsx
  src/components/editor.tsx
  src/components/scope/scope-item.tsx
  src/components/scope/scope-view-mode.tsx
  src/components/ui/popover.tsx
  src/utils/codemirror-themes.tsx
Labels: feature, accepted

#66 fix: wrap option
  src/components/wrap.tsx
Labels: bug

#69 chore: Add sponsors to README
  .github/workflows/update-readme.yml
  README.md
  package-lock.json
  package.json
  tools/commit-readme.sh
  tools/update-readme.js
Labels: chore

#49 feat: Generate sharable link for code-explorer
  src/hooks/use-explorer.ts
Labels: feature
