Repository eslint/code-explorer, pull requests merged in 2025-04, with the labels that each got.

#89 fix: tree view horizontal scrolling to prevent node collapse
  src/components/ast/css-ast.tsx
  src/components/ast/javascript-ast.tsx
  src/components/ast/json-ast.tsx
  src/components/ast/markdown-ast.tsx
  src/components/scope/index.tsx
Labels: bug

#91 refactor: remove accordion behavior for non-array nodes
  src/components/scope/scope-item.tsx
Labels: chore, contributor pool

#90 fix: layout improvements
  src/App.tsx
  src/components/ast/css-ast.tsx
  src/components/ast/javascript-ast.tsx
  src/components/ast/json-ast.tsx
  src/components/ast/markdown-ast.tsx
  src/components/editor.tsx
  src/components/scope/index.tsx
Labels: bug, contributor pool

#92 feat: add support for Markdown Front Matter parsing
  package-lock.json
  package.json
  src/components/options.tsx
  src/hooks/use-ast.ts
  src/hooks/use-explorer.ts
  src/lib/const.ts
Labels: feature, contributor pool

#93 feat: make tree entry keys toggleable
  src/components/tree-entry.tsx
Labels: feature, contributor pool

#94 chore: migrate to ESLint v9
  eslint.config.mjs
  package-lock.json
  package.json
Labels: chore
