Repository eslint/code-explorer, pull requests merged in 2025-05, with the labels that each got.

#95 chore: rename `fmt` script to follow general convention
  .github/workflows/ci.yml
  package.json
Labels: chore

#96 feat: add support for `allowTrailingCommas` option in JSON
  package-lock.json
  package.json
  src/components/options.tsx
  src/hooks/use-ast.ts
  src/hooks/use-explorer.ts
  src/lib/const.ts
Labels: feature, accepted

#103 refactor: add missing type to `JavaScriptPanel`
  src/components/options.tsx
Labels: chore

#104 feat: change ESQuery Selector placeholder text based on language
  src/components/esquery-selector-input.tsx
  src/lib/const.ts
Labels: feature, accepted

#101 fix: Adding missing field to store
  src/hooks/use-explorer.ts
Labels: bug, accepted, chore

#107 chore: remove setting default code as we are rehydrating store
  src/components/options.tsx
Labels: chore

#105 chore: cleanup and update `.gitignore`
  .gitignore
Labels: accepted, chore
