Repository eslint/code-explorer, pull requests merged in 2025-06, with the labels that each got.

#109 perf: add React Compiler
  eslint.config.mjs
  package-lock.json
  package.json
  src/components/path/index.tsx
  vite.config.ts
Labels: accepted, chore

#106 docs: add step with example selector for new language
  docs/adding-languages.md
Labels: documentation, accepted, chore

#112 fix: update incorrect `meta` properties
  index.html
  public/manifest.json
Labels: bug, accepted

#111 feat: add JSON frontmatter support
  package-lock.json
  package.json
  src/hooks/use-explorer.ts
  src/lib/const.ts
Labels: feature, accepted, contributor pool
